baseURL: "https://NesGQ.github.io/" 
title: Néstor González-Quintero
theme: PaperMod 

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
          # url: books/
          # weight: 5 
        - name: Research
          url: research/
          weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        - name: Teaching
          url: teaching/
          weight: 3
        - name: Miscellaneous
          url: misc/
          weight: 4
        - name: Personal
          url: personal/
          weight: 5 
        # - name: Blog
          # url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          # weight: 6

params:
    description: "This website hosts Néstor González-Quintero's research papers, course materials, curriculum vitae, and contact information."
    author: Néstor González-Quintero
    keywords: ["macroeconomics", "monetary policy", "international macroeconomics", "development economics", "University of Nottingham", "economist", "unconventional monetary policy", "monetary union"]
    googleAnalyticsID: "G-RKYFLMM7W7"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","teaching","miscellaneous","personal"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Néstor González-Quintero
          subtitle: "I am currently a Teaching Associate in the School of Economics at the University of Nottingham, UK. My research interests lie at the intersection of macroeconomic policy analysis, international macroeconomics and development macroeconomics."
          imageUrl: "picture_nesgq.jpeg"
          imageWidth: 160
          imageHeight: 190
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: Miscellaneous
              url: misc/
            - name: Personal
              url: personal/
            # - name: Courses
            #   url: courses/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:Nestor.GonzalezQuintero1@nottingham.ac.uk
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/NesGQ
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: X
          url: https://x.com/NesGQ
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social
        - name: LinkedIn
          url: https://www.linkedin.com/in/nestorgq/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Néstor González-Quintero"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2